name: Release Docker Images (Ascend NPU)
on:
  push:
    tags:
      - "*" # Trigger on all tags and filterred by pep440 later
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        cann_version: ['8.2.rc1.alpha003']
        os: ['ubuntu22.04']
        python_version: ['py3.11']
        device_type: ['a3']
        kernel_npu_tag: ['20250802']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true
          docker-images: false

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository_owner }}/sglang
          tags: |
            type=pep440,event={{raw}}
          flavor: |
            suffix: -cann${{ matrix.cann_version }}-${{ matrix.device_type }}-${{ matrix.os }}-${{ matrix.python_version }},onlatest=true
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile.npu
          # TODO: need add x86 platforms support when memfabric is ready
          platforms: linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          provenance: false
          build-args: |
            SGLANG_KERNEL_NPU_TAG=${{ matrix.kernel_npu_tag }}
            CANN_VERSION=${{ matrix.cann_version }}
            DEVICE_TYPE=${{ matrix.device_type }}
            OS=${{ matrix.os }}
            PYTHON_VERSION=${{ matrix.python_version }}