name: Release Docker Images (Ascend NPU)
on:
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true
          docker-images: false

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            lmsysorg/sglang:
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=pep440,pattern={{raw}}
          flavor:
            latest=false

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          version=$(cat python/sglang/version.py | cut -d'"' -f2)
          # TODO: need made the tag build by matrix
          tag=v${version}-cann8.2.rc1.alpha003-ubuntu22.04-py3.11

          docker build . -f docker/Dockerfile.npu --build-arg SGLANG_KERNEL_NPU_TAG=20250802  -t lmsysorg/sglang:${tag} --no-cache
          docker push ${{ github.repository_owner }}/sglang:${tag}
